Add time-lock functionality - IO1-2302
ssvlabs/ssv-network pull request #181
Opened 2023-02-07 00:42 UTC by mtabasco

Implementation of time-locked functionality to these functions:
`UpdateNetworkFee`
`WithdrawNetworkEarnings`
`UpdateLiquidationThresholdPeriod`

How it works:
1. The `owner` calls one of these functions with a specific parameter.
2. For that call (function + parameter), the lock period starts (2 days, constant). The event `FunctionLocked` is emitted.
3. If the `owner` calls the function with the same parameter before the _release_ time, the transaction is reverted with the `FunctionLocked` error.
4. Only after the 2 days period passes, the function can be executed by the `owner`.

There could be multiple locked executions at the same time, for example:
`UpdateNetworkFee(200000000)` at Tue 7 Feb, 1:40
`UpdateNetworkFee(350000000)`at Tue 8 Feb, 11:20
...
Everyone will have its own _release_ time.

As this functionality is expected to be used by authorized accounts and consumed after scheduled, there is no implementation for deleting unused time-locked schedules.

2023-02-13 13:52 UTC, mtabasco commented on contracts/SSVNetwork.sol
> +            emit FunctionLocked(selector, releaseTime, msg.sender);
msg.sender redundant?

2023-02-15 12:53 UTC, andrew-blox commented on contracts/SSVNetwork.sol
> +            if(shrunkAmount > dao_.networkBalance(network.networkFee)) {
Please just double check that dao_.networkBalance(network.networkFee) is returning a shrunk amount not expanded.

2023-02-15 14:58 UTC, lior-blox commented
@mtabasco @andrew-blox 
a. we need to know based on event what type of lock was emitted
b. and to know how to parse it.-> add to readme with example - timelock.readme

2023-02-17 11:15 UTC, mtabasco commented
> @mtabasco @andrew-blox a. we need to know based on event what type of lock was emitted b. and to know how to parse it.-> add to readme with example - timelock.readme c. list of all operations/functions that are bound to timelock

Done

2023-02-20 13:55 UTC, andrew-blox requested changes

2023-02-20 13:55 UTC, andrew-blox commented on TIMELOCK.md
> +1. The contract owner calls the time-locked fucntion with the required parameters.
fucntion - change to function

2023-02-20 13:55 UTC, andrew-blox commented on TIMELOCK.md
> +const functionData = ssvNetwork.interface.decodeFunctionData('updateNetworkFee', decodedLog.functionData);
I am prob wrong but do we need any dependencies to run this code?  For example we have `decodeFunctionData` and i dont see any requires here other then the abi

2023-02-21 11:39 UTC, andrew-blox approved these changes

2025-03-10 09:32 UTC, closed without merging